[package]
name = "taskrunner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

task_01 = { path = "../tasks/task_01" }
task_02 = { path = "../tasks/task_02" }